version: "3.9"

services:
  redis:
    container_name: redis
    image: redis
    restart: unless-stopped
  backend:
    container_name: backend
    build: ./example-backend
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
  frontend:
    container_name: frontend
    build: ./example-frontend
    ports:
      - "5000:5000"
  