version: "3.9"

services:
  backend:
    container_name: backend
    environment:
      REDIS_HOST: redis
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
      REQUEST_ORIGIN: http://localhost:80
    build: ./example-backend
    depends_on:
      - redis
      - postgres
      - nginx
  frontend:
    container_name: frontend
    environment:
      REACT_APP_BACKEND_URL: http://localhost:80
    build: ./example-frontend
  redis:
    container_name: redis
    image: redis
    restart: unless-stopped
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
  nginx:
    container_name: nginx
    image: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
