version: '3.8'

services:
  frontend:
    container_name: frontend
    build: ./ml-kurkkumopo-frontend
    ports:
      - 3000:3000

  backend:
    container_name: backend
    build: ./ml-kurkkumopo-backend
    ports:
      - 5000:5000
    volumes:
      - model:/src/model

  training:
    container_name: training
    build: ./ml-kurkkumopo-training
    volumes:
      - model:/src/model
      - images:/src/imgs
      - data:/src/data

volumes:
  model:
  images:
  data:
