version: "3.9"

services:
  frontend:
    container_name: frontend
    build: ./example-frontend
    ports:
      - "5000:5000"
  
  backend:
    container_name: backend
    build: ./example-backend
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=pg_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    depends_on:
      - redis
      - pg_db
  
  redis:
    container_name: redis
    image: redis
    restart: unless-stopped

  pg_db:
    container_name: pg_db
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres